Repository griptape-ai/griptape-nodes, pull requests merged in 2025-06, with the labels that each got.

#1471 fix: add cache morning parameter to download url responses
  src/griptape_nodes/retained_mode/managers/static_files_manager.py
Labels: bug

#1475 Adding Claude Code auto-gen CLAUDE.md. Gives context for Claude copilot working with Griptape Nodes.
  CLAUDE.md
Labels: enhancement

#1495 feat: install library deps relative to install location
  src/griptape_nodes/retained_mode/managers/library_manager.py
Labels: enhancement

#1494 Add profiling as an extra. Adds VSCode tasks to facilitate profiling from within the IDE.
  .gitignore
  .vscode/settings.json
  .vscode/tasks.json
  CLAUDE.md
  pyproject.toml
  uv.lock
Labels: enhancement, performance

#1295 Added friendlier error message if image URL failed to download. Happens with shared workflows or if staticfiles gets wiped.
  libraries/griptape_nodes_advanced_media_library/controlnet_aux_nodes_library/anyline_detector.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/controlnet/flux_control_net_parameters.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/controlnet/union_one_flux_control_net_model.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/controlnet/union_two_flux_control_net_parameters.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/diptych_flux_fill_pipeline_parameters.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/flux_fill_pipeline_parameters.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/tiling_flux_img_2_img_pipeline.py
  libraries/griptape_nodes_advanced_media_library/opencv_nodes_library/canny_convert_image.py
  libraries/griptape_nodes_advanced_media_library/pillow_nodes_library/gaussian_blur_image.py
  libraries/griptape_nodes_advanced_media_library/pillow_nodes_library/grayscale_convert_image.py
  libraries/griptape_nodes_advanced_media_library/pillow_nodes_library/rescale_image.py
  libraries/griptape_nodes_advanced_media_library/spandrel_nodes_library/tiling_span.py
  libraries/griptape_nodes_advanced_media_library/transformers_nodes_library/depth_anything_for_depth_estimation.py
  libraries/griptape_nodes_advanced_media_library/utils/__init__.py
  libraries/griptape_nodes_advanced_media_library/utils/image_utils.py
  libraries/griptape_nodes_library/griptape_nodes_library/image/describe_image.py
  libraries/griptape_nodes_library/griptape_nodes_library/image/save_image.py
  libraries/griptape_nodes_library/griptape_nodes_library/utils/image_utils.py
Labels: enhancement, engine

#1559 fix: only cache bust local storage driver
  src/griptape_nodes/drivers/storage/local_storage_driver.py
  src/griptape_nodes/retained_mode/managers/static_files_manager.py
Labels: bug

#1582 refactor: remove legacy SSE app code
  pyproject.toml
  src/griptape_nodes/app/__init__.py
  src/griptape_nodes/app/app.py
  src/griptape_nodes/app/app_websocket.py
  src/griptape_nodes/app/nodes_api_socket_manager.py
  src/griptape_nodes/retained_mode/managers/event_manager.py
Labels: refactor

#1584 Eliminate spurious workflow warning, eliminate legacy workflows/templates/ dir as being included in default workflows to load
  src/griptape_nodes/retained_mode/managers/settings.py
  src/griptape_nodes/retained_mode/managers/workflow_manager.py
Labels: bug

#1589 fix: load GT_CLOUD_API_KEY using secrets manager
  src/griptape_nodes/app/app.py
Labels: bug
