Repository griptape-ai/griptape-nodes, pull requests merged in 2025-05, with the labels that each got.

#758 Cancellation/Error Improvements
  src/griptape_nodes/exe_types/flow.py
  src/griptape_nodes/machines/node_resolution.py
  src/griptape_nodes/retained_mode/managers/flow_manager.py
Labels: bug

#757 fix: handle dictionaries that look like image url artifacts
  nodes/griptape_nodes_library/image/load_image.py
  nodes/griptape_nodes_library/image/save_image.py
  nodes/griptape_nodes_library/utils/image_utils.py
Labels: bug

#779 refactor: make "Node hasn't begun yet" text placeholder text
  nodes/griptape_nodes_library/agents/agent.py
  nodes/griptape_nodes_library/image/create_image.py
  workflows/templates/compare_prompts.py
  workflows/templates/photography_team.py
Labels: refactor

#767 refactor: separate updater into dedicated process
  docs/faq.md
  pyproject.toml
  src/griptape_nodes/__init__.py
  src/griptape_nodes/updater/__init__.py
Labels: refactor

#781 fix: use correct keys for validation in compare image
  src/griptape_nodes/traits/compare_images.py
Labels: bug

#783 feat: add cycle detection
  src/griptape_nodes/machines/node_resolution.py
  src/griptape_nodes/retained_mode/managers/flow_manager.py
Labels: enhancement

#791 refactor: make load/save image operate on image url artifacts
  nodes/griptape_nodes_library/image/load_image.py
  nodes/griptape_nodes_library/image/save_image.py
  nodes/griptape_nodes_library/utils/image_utils.py
Labels: refactor

#795 fix: safely cancel flow run rather than taking the whole engine down
  src/griptape_nodes/retained_mode/managers/flow_manager.py
Labels: bug

#797 feat: install assets during auto update
  src/griptape_nodes/__init__.py
Labels: enhancement

#815 add Settings > Copy Path to Settings to FAQ
  docs/faq.md
Labels: documentation

#820 Secret Improvements
  src/griptape_nodes/__init__.py
  src/griptape_nodes/retained_mode/griptape_nodes.py
  src/griptape_nodes/retained_mode/managers/secrets_manager.py
  src/griptape_nodes/retained_mode/managers/workflow_manager.py
Labels: bug

#724 Ftue
  docs/faq.md
  docs/ftue/00_tour/FTUE_00_tour.md
  docs/ftue/00_tour/assets/connected.png
  docs/ftue/00_tour/assets/create_from_scratch.png
  docs/ftue/00_tour/assets/create_nodes_panel.png
  docs/ftue/00_tour/assets/landing_page.png
  docs/ftue/00_tour/assets/launch_link.png
  docs/ftue/00_tour/assets/nodes_in_workspace.png
  docs/ftue/00_tour/assets/workspace_interface.png
  docs/ftue/01_prompt_an_image/FTUE_01_prompt_an_image.md
  docs/ftue/01_prompt_an_image/assets/generate_image_node.png
  docs/ftue/01_prompt_an_image/assets/potato_aerobics.png
  docs/ftue/01_prompt_an_image/assets/potato_painting.png
  docs/ftue/01_prompt_an_image/assets/prompt_image_example.png
  docs/ftue/01_prompt_an_image/assets/text_prompt_field.png
  docs/ftue/02_translator/FTUE_02_translator.md
  docs/ftue/02_translator/assets/build_your_own.png
  docs/ftue/02_translator/assets/connect_your_own.png
  docs/ftue/02_translator/assets/exec_chain.png
  docs/ftue/02_translator/assets/final_result.png
  docs/ftue/02_translator/assets/mandarin.png
  docs/ftue/02_translator/assets/mandarin_display.png
  docs/ftue/02_translator/assets/mandarin_merge.png
  docs/ftue/02_translator/assets/mandarin_to_english.png
  docs/ftue/02_translator/assets/summary_pre.png
  docs/ftue/02_translator/assets/translator_example.png
  docs/ftue/02_translator/assets/workflow_overview.png
  docs/ftue/02_translator/assets/workflow_result.png
  docs/ftue/03_compare_prompts/FTUE_03_compare_prompts.md
  docs/ftue/03_compare_prompts/assets/agent_node_output.png
  docs/ftue/03_compare_prompts/assets/basic_image_node.png
  docs/ftue/03_compare_prompts/assets/bespoke_prompt_image.png
  docs/ftue/03_compare_prompts/assets/compare_prompts_example.png
  docs/ftue/03_compare_prompts/assets/compare_prompts_workflow.png
  docs/ftue/03_compare_prompts/assets/detailed_instructions.png
  docs/ftue/03_compare_prompts/assets/enhanced_prompt_image.png
  docs/ftue/04_photography_team/FTUE_04_photography_team.md
  docs/ftue/04_photography_team/assets/agent_tool_conversion.png
  docs/ftue/04_photography_team/assets/cinematographer_ruleset.png
  docs/ftue/04_photography_team/assets/orchestrator_setup.png
  docs/ftue/04_photography_team/assets/photography_team_example.png
  docs/ftue/04_photography_team/assets/ruleset_list.png
  docs/ftue/04_photography_team/assets/tool_list.png
  docs/ftue/04_photography_team/assets/tools_concept.png
  docs/ftue/04_photography_team/assets/workflow_overview.png
  docs/ftue/04_photography_team/assets/workflow_result.png
  docs/ftue/FTUE.md
  docs/ftue/assets/FTUE_01_prompt_an_image.png
  docs/ftue/assets/FTUE_02_translator.png
  docs/ftue/assets/FTUE_03_compare_prompts.png
  docs/ftue/assets/FTUE_04_photography_team.png
  docs/getting_started.md
  mkdocs.yml
Labels: documentation

#880 refactor: painfully add github links to ALL TODOs
  nodes/diffusers_nodes_library/flux_pipeline.py
  nodes/diffusers_nodes_library/tiling_flux_img_2_img_pipeline.py
  nodes/diffusers_nodes_library/utils/lora_utils.py
  nodes/diffusers_nodes_library/utils/tiling_image_processor.py
  nodes/diffusers_nodes_library/utils/torch_utils.py
  nodes/griptape_nodes_library/agents/agent.py
  nodes/griptape_nodes_library/config/base_driver.py
  nodes/griptape_nodes_library/config/prompt/amazon_bedrock_prompt.py
  nodes/griptape_nodes_library/config/prompt/ollama_prompt_driver.py
  nodes/griptape_nodes_library/config/web_search/web_search_drivers.py
  nodes/griptape_nodes_library/image/create_image.py
  nodes/griptape_nodes_library/image/describe_image.py
  nodes/pillow_nodes_library/rescale_image.py
  nodes/spandrel_nodes_library/tiling_span.py
  pyproject.toml
  src/griptape_nodes/app/app.py
  src/griptape_nodes/app/nodes_api_socket_manager.py
  src/griptape_nodes/exe_types/connections.py
  src/griptape_nodes/exe_types/core_types.py
  src/griptape_nodes/exe_types/node_types.py
  src/griptape_nodes/exe_types/type_validator.py
  src/griptape_nodes/machines/node_resolution.py
  src/griptape_nodes/retained_mode/events/base_events.py
  src/griptape_nodes/retained_mode/griptape_nodes.py
  src/griptape_nodes/retained_mode/managers/config_manager.py
  src/griptape_nodes/retained_mode/managers/flow_manager.py
  src/griptape_nodes/retained_mode/managers/library_manager.py
  src/griptape_nodes/retained_mode/managers/node_manager.py
  src/griptape_nodes/retained_mode/managers/object_manager.py
  src/griptape_nodes/retained_mode/managers/workflow_manager.py
  src/griptape_nodes/retained_mode/retained_mode.py
Labels: refactor

#907 fix: improve fallback json encoding of events
  src/griptape_nodes/retained_mode/events/base_events.py
Labels: bug

#824 fix: catch bad configs when adding values
  src/griptape_nodes/retained_mode/managers/config_manager.py
Labels: bug

#910 feat: install from pypi rather than git
  install.ps1
  install.sh
Labels: enhancement

#823 Fix Auto Restart
  src/griptape_nodes/__init__.py
  src/griptape_nodes/updater/__init__.py
Labels: bug

#916 feat: prompt user on whether they'd like to register library extras
  src/griptape_nodes/__init__.py
  src/griptape_nodes/app/app.py
  src/griptape_nodes/retained_mode/managers/config_manager.py
  src/griptape_nodes/retained_mode/managers/settings.py
  src/griptape_nodes/retained_mode/managers/static_files_manager.py
Labels: enhancement

#930 refactor: move rich handler to app
  src/griptape_nodes/app/app.py
  src/griptape_nodes/retained_mode/griptape_nodes.py
Labels: refactor

#943 feat: show spinner while loading expensive imports
  src/griptape_nodes/__init__.py
Labels: enhancement

#938 FTUE_01 upgrades
  docs/ftue/01_prompt_an_image/FTUE_01_prompt_an_image.md
  docs/ftue/01_prompt_an_image/assets/nav_bar.png
  docs/ftue/01_prompt_an_image/assets/node_running.gif
  docs/ftue/01_prompt_an_image/assets/potato_aerobics.png
  docs/ftue/01_prompt_an_image/assets/potato_painting.png
  docs/ftue/01_prompt_an_image/assets/prompt_image_example.png
  docs/ftue/01_prompt_an_image/assets/ways_to_run.png
  docs/ftue/02_translator/assets/node_running.gif
Labels: documentation

#933 FTUE_00 upgrades
  docs/ftue/00_tour/FTUE_00_tour.md
  docs/ftue/00_tour/assets/connected.png
  docs/ftue/00_tour/assets/create_from_scratch.png
  docs/ftue/00_tour/assets/create_node_dblClick.gif
  docs/ftue/00_tour/assets/create_node_dragDrop.gif
  docs/ftue/00_tour/assets/create_node_spacebar.gif
  docs/ftue/00_tour/assets/eg_prompt.png
  docs/ftue/00_tour/assets/landing_page.png
  docs/ftue/00_tour/assets/nodes_in_workspace.png
  docs/ftue/00_tour/assets/run_node.png
  docs/ftue/00_tour/assets/workspace_interface.png
Labels: documentation

#958 this may be the only workflow console image recapture
  docs/ftue/00_tour/assets/workspace_interface.png
Labels: documentation

#671 first-draft HF install docs (ended up just doing nodes at same time)
  docs/ftue/01_prompt_an_image/assets/run_options.png
  docs/nodes/hugging_face/assets/00_HF_MainPage.png
  docs/nodes/hugging_face/assets/01_HF_signup.png
  docs/nodes/hugging_face/assets/02_HF_Settings.png
  docs/nodes/hugging_face/assets/03_HF_AccessTokens.png
  docs/nodes/hugging_face/assets/04_HF_TokenRead.png
  docs/nodes/hugging_face/assets/05_HF_SaveToken.png
  docs/nodes/hugging_face/assets/06_GN_Settings.png
  docs/nodes/hugging_face/assets/07_GN_HFToken.png
  docs/nodes/hugging_face/assets/gated_model.png
  docs/nodes/hugging_face/flux_pipeline.md
  docs/nodes/hugging_face/hugging_face_install.md
  docs/nodes/hugging_face/pillow_resize.md
  docs/nodes/hugging_face/tiling_flux_img_2_img_pipeline.md
  docs/nodes/hugging_face/tiling_spandrel_pipeline.md
  mkdocs.yml
Labels: documentation

#959 fix: prompt user to press enter after manually updating on windows
  src/griptape_nodes/updater/__init__.py
Labels: bug

#982 fix: handle more status codes when connecting to API
  src/griptape_nodes/__init__.py
  src/griptape_nodes/app/nodes_api_socket_manager.py
Labels: bug

#966 moved "next step" notes 500px right
  workflows/templates/compare_prompts.py
  workflows/templates/coordinating_agents.py
  workflows/templates/photography_team.py
  workflows/templates/prompt_an_image.py
Labels: ftue

#961 prepend "lesson #:" through FTUE titles
  docs/ftue/01_prompt_an_image/FTUE_01_prompt_an_image.md
  docs/ftue/02_coordinating_agents/FTUE_02_coordinating_agents.md
  docs/ftue/03_compare_prompts/FTUE_03_compare_prompts.md
  docs/ftue/04_photography_team/FTUE_04_photography_team.md
  docs/ftue/FTUE.md
Labels: documentation

#981 refactor: use pypi version of griptape
  install.ps1
  install.sh
  pyproject.toml
  uv.lock
Labels: refactor

#985 feat: support registering all workflows in a directory
  src/griptape_nodes/retained_mode/managers/library_manager.py
  src/griptape_nodes/retained_mode/managers/settings.py
  src/griptape_nodes/retained_mode/managers/workflow_manager.py
Labels: enhancement

#990 fix: update shell during installation
  install.ps1
  install.sh
Labels: bug

#1000 proposed relo of HF> AM docs (advanced media)
  docs/how_to/assets/00_HF_MainPage.png
  docs/how_to/assets/01_HF_signup.png
  docs/how_to/assets/02_HF_Settings.png
  docs/how_to/assets/03_HF_AccessTokens.png
  docs/how_to/assets/04_HF_TokenRead.png
  docs/how_to/assets/05_HF_SaveToken.png
  docs/how_to/assets/06_GN_Settings.png
  docs/how_to/assets/07_GN_HFToken.png
  docs/how_to/assets/gated_model.png
  docs/how_to/hugging_face_install.md
  docs/nodes/advanced_media_library/flux_pipeline.md
  docs/nodes/advanced_media_library/pillow_resize.md
  docs/nodes/advanced_media_library/tiling_flux_img_2_img_pipeline.md
  docs/nodes/advanced_media_library/tiling_spandrel_pipeline.md
  mkdocs.yml
Labels: documentation

#1007 refactor: remove auto restart after update
  src/griptape_nodes/__init__.py
  src/griptape_nodes/updater/__init__.py
Labels: refactor

#1016 added safety guidance to enhance_prompt
  libraries/griptape_nodes_library/griptape_nodes_library/image/create_image.py
Labels: nodes

#1012 feat: accept request events on local static server
  CONTRIBUTING.md
  src/griptape_nodes/app/app.py
  src/griptape_nodes/retained_mode/events/static_file_events.py
  src/griptape_nodes/retained_mode/managers/event_manager.py
Labels: enhancement

#1017 1001 ftue 03 upgrades
  docs/ftue/03_compare_prompts/FTUE_03_compare_prompts.md
  docs/ftue/03_compare_prompts/assets/compare_prompts_example.png
  docs/ftue/03_compare_prompts/assets/trace_basic.png
  docs/ftue/03_compare_prompts/assets/trace_bespoke.png
  docs/ftue/03_compare_prompts/assets/trace_enhanced.png
Labels: documentation

#1021 enhanced prompt guidance change
  libraries/griptape_nodes_library/griptape_nodes_library/image/create_image.py
Labels: nodes

#1011 fix: strip ansi escape characters in response
  src/griptape_nodes/retained_mode/managers/arbitrary_code_exec_manager.py
Labels: retained mode

#1019 Setting Config Should Reload Merged Config
  src/griptape_nodes/retained_mode/managers/config_manager.py
Labels: bug

#1025 fix: output image url artifact from advanced library
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/flux_pipeline.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/tiling_flux_img_2_img_pipeline.py
  libraries/griptape_nodes_advanced_media_library/pillow_nodes_library/rescale_image.py
  libraries/griptape_nodes_advanced_media_library/pillow_nodes_library/utils.py
  libraries/griptape_nodes_advanced_media_library/spandrel_nodes_library/tiling_span.py
Labels: bug

#1032 Feature/grok_image_driver
  docs/nodes/config/griptape_cloud_image_driver.md
  docs/nodes/config/grok_image_driver.md
  docs/nodes/config/openai_image_driver.md
  libraries/griptape_nodes_library/griptape_nodes_library.json
  libraries/griptape_nodes_library/griptape_nodes_library/config/image/grok_image_driver.py
  mkdocs.yml
Labels: enhancement

#1041 FTUE_04 updated
  docs/ftue/04_photography_team/FTUE_04_photography_team.md
  docs/ftue/04_photography_team/assets/rule_ruleset_agent_tool_chain.png
  docs/ftue/04_photography_team/assets/ruleset_direct_connect.png
  docs/ftue/04_photography_team/assets/workflow_result.png
Labels: documentation

#1049 tiles to updated names
  docs/ftue/00_tour/assets/create_from_scratch.png
  docs/ftue/01_prompt_an_image/assets/prompt_image_example.png
  docs/ftue/02_coordinating_agents/assets/coordinating_agents_example.png
  docs/ftue/03_compare_prompts/assets/compare_prompts_example.png
  docs/ftue/04_photography_team/assets/photography_team_example.png
Labels: documentation

#1051 fix: verify parameter lists are populated
  libraries/griptape_nodes_library/griptape_nodes_library/agents/agent.py
Labels: bug

#1063 ci: create github workflow for nightly releases
  .github/workflows/nightly-release.yml
  .github/workflows/release.yml
  Makefile
Labels: ci

#1065 feat: sync assets based on current engine version
  src/griptape_nodes/__init__.py
  src/griptape_nodes/updater/__init__.py
Labels: enhancement

#1070 feat: change auto-update logic based on install source
  src/griptape_nodes/__init__.py
Labels: enhancement

#1071 ci: release latest twice a day
  .github/workflows/latest-release.yml
Labels: ci

#1076 feat: set empty secret value when setting config value starting with $
  src/griptape_nodes/retained_mode/managers/config_manager.py
Labels: refactor

#1073 fix: download assets from 'latest' tag unless installed from stable pypi
  src/griptape_nodes/__init__.py
Labels: bug, installer

#1060 Openai key-docs
  docs/how_to/installs/assets/huggingface_00_MainPage.png
  docs/how_to/installs/assets/huggingface_01_signup.png
  docs/how_to/installs/assets/huggingface_02_Settings.png
  docs/how_to/installs/assets/huggingface_03_AccessTokens.png
  docs/how_to/installs/assets/huggingface_04_TokenRead.png
  docs/how_to/installs/assets/huggingface_05_SaveToken.png
  docs/how_to/installs/assets/huggingface_06_gated_model.png
  docs/how_to/installs/assets/huggingface_07_GN_Settings.png
  docs/how_to/installs/assets/huggingface_08_GN_HFToken.png
  docs/how_to/installs/hugging_face.md
  docs/how_to/keys/assets/openai_00_main_page.png
  docs/how_to/keys/assets/openai_01_login_api_platform.png
  docs/how_to/keys/assets/openai_02_dashboard.png
  docs/how_to/keys/assets/openai_03_api_keys.png
  docs/how_to/keys/assets/openai_04_create_new_secret_key_button.png
  docs/how_to/keys/assets/openai_05_create_new_secret_key_modal.png
  docs/how_to/keys/assets/openai_06_gtn_settings.png
  docs/how_to/keys/openai.md
  docs/nodes/advanced_media_library/flux_pipeline.md
  docs/nodes/advanced_media_library/tiling_flux_img_2_img_pipeline.md
  docs/nodes/advanced_media_library/tiling_spandrel_pipeline.md
  mkdocs.yml
Labels: documentation

#1087 deps: update griptape
  pyproject.toml
  uv.lock
Labels: bug

#1091 fix: use correct url for pypi auto updates
  src/griptape_nodes/__init__.py
Labels: bug

#1092 fix: properly parse install_source when syncing assets
  src/griptape_nodes/__init__.py
Labels: bug

#1094 ci: use PAT token so that workflows can trigger other workflows
  .github/workflows/latest-tag.yml
Labels: ci

#1085 1080 create a grok key tut
  docs/how_to/keys/assets/grok_00_main_page.png
  docs/how_to/keys/assets/grok_01_console_login.png
  docs/how_to/keys/assets/grok_02_signup.png
  docs/how_to/keys/assets/grok_03_billing.png
  docs/how_to/keys/assets/grok_04_key_links.png
  docs/how_to/keys/assets/grok_05_create_api_key_button.png
  docs/how_to/keys/assets/grok_06_create_api_key_page.png
  docs/how_to/keys/assets/grok_07_gtn_settings.png
  docs/how_to/keys/assets/gtn_settings_menu.png
  docs/how_to/keys/grok.md
  docs/how_to/keys/openai.md
  mkdocs.yml
Labels: documentation

#1113 AVM install added to FAQ
  docs/faq.md
Labels: documentation

#1119 fix: show loader earlier
  src/griptape_nodes/__init__.py
Labels: bug

#1116 GrokPrompt doc
  docs/nodes/config/grok_prompt_driver.md
  mkdocs.yml
Labels: documentation

#1120 fix: don't re-init engine on SSE error
  src/griptape_nodes/app/app.py
Labels: bug

#1135 updated layout for compare_prompts
  docs/ftue/03_compare_prompts/assets/compare_prompts_workflow.png
  docs/ftue/03_compare_prompts/assets/trace_basic.png
  docs/ftue/03_compare_prompts/assets/trace_bespoke.png
  docs/ftue/03_compare_prompts/assets/trace_enhanced.png
  libraries/griptape_nodes_library/workflows/templates/compare_prompts.py
Labels: ftue

#1137 fix: handle reconnection error specially to avoid reconnect delay
  src/griptape_nodes/app/app.py
Labels: bug

#1128 feat: support registering libraries from requirement specifier
  pyproject.toml
  src/griptape_nodes/retained_mode/events/library_events.py
  src/griptape_nodes/retained_mode/managers/library_manager.py
  uv.lock
Labels: enhancement

#197 feat: add make run/watch live reload command
  CONTRIBUTING.md
  Makefile
  pyproject.toml
  src/griptape_nodes/app/watch.py
  uv.lock
Labels: enhancement

#1162 adds a Compare Numbers node
  libraries/griptape_nodes_library/griptape_nodes_library.json
  libraries/griptape_nodes_library/griptape_nodes_library/execution/compare_numbers.py
Labels: nodes

#1143 Add and refactor advanced flux nodes - controlnet, loras, params
  libraries/griptape_nodes_advanced_media_library/controlnet_aux_nodes_library/__init__.py
  libraries/griptape_nodes_advanced_media_library/controlnet_aux_nodes_library/anyline_detector.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/__init__.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/misc/__init__.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/misc/tiling_image_processor.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/parameters/__init__.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/parameters/file_path_parameter.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/parameters/huggingface_model_parameter.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/parameters/huggingface_repo_file_parameter.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/parameters/huggingface_repo_parameter.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/parameters/log_parameter.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/utils/__init__.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/utils/huggingface_utils.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/utils/logging_utils.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/utils/math_utils.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/utils/option_utils.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/utils/torch_utils.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/utils/ui_option_utils.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/flux_pipeline.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/__init__.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/__init__.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/controlnet/__init__.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/controlnet/flux_control_net_parameters.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/controlnet/union_flux_control_net_pipeline.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/controlnet/union_one_flux_control_net_model.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/controlnet/union_pro_flux_control_net_pipeline.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/controlnet/union_pro_two_flux_control_net_pipeline.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/controlnet/union_two_flux_control_net_parameters.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/flux_loras_parameter.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/flux_pipeline.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/flux_pipeline_memory_footprint.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/flux_pipeline_parameters.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/lora/__init__.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/lora/flux_lora_from_file.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/lora/flux_lora_parameters.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/lora/huggingface_flux_lora.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/lora/lumatales_flux_lora.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/lora/micro_landscape_on_phone_flux_lora.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/lora/miniature_world_flux_lora.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/pipelines/flux/tiling_flux_img_2_img_pipeline.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/tiling_flux_img_2_img_pipeline.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/utils/__init__.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/utils/huggingface_utils.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/utils/logging_utils.py
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/utils/lora_utils.py
  libraries/griptape_nodes_advanced_media_library/griptape_nodes_library.json
  libraries/griptape_nodes_advanced_media_library/opencv_nodes_library/__init__.py
  libraries/griptape_nodes_advanced_media_library/opencv_nodes_library/canny_convert_image.py
  libraries/griptape_nodes_advanced_media_library/pillow_nodes_library/gaussian_blur_image.py
  libraries/griptape_nodes_advanced_media_library/pillow_nodes_library/grayscale_convert_image.py
  libraries/griptape_nodes_advanced_media_library/pillow_nodes_library/rescale_image.py
  libraries/griptape_nodes_advanced_media_library/pillow_nodes_library/utils.py
  libraries/griptape_nodes_advanced_media_library/spandrel_nodes_library/tiling_span.py
  libraries/griptape_nodes_advanced_media_library/spandrel_nodes_library/utils.py
  libraries/griptape_nodes_advanced_media_library/transformers_nodes_library/__init__.py
  libraries/griptape_nodes_advanced_media_library/transformers_nodes_library/depth_anything_for_depth_estimation.py
  libraries/griptape_nodes_library/griptape_nodes_library.json
Labels: enhancement

#1174 refactor: remove reliance on griptape's SingletonMixin
  src/griptape_nodes/exe_types/type_validator.py
  src/griptape_nodes/node_library/library_registry.py
  src/griptape_nodes/node_library/workflow_registry.py
  src/griptape_nodes/retained_mode/events/payload_registry.py
  src/griptape_nodes/retained_mode/griptape_nodes.py
  src/griptape_nodes/traits/trait_registry.py
  src/griptape_nodes/utils/metaclasses.py
Labels: refactor

#1177 Reapply "refactor: remove reliance on griptape's SingletonMixin (#1174)"
  src/griptape_nodes/exe_types/type_validator.py
  src/griptape_nodes/node_library/library_registry.py
  src/griptape_nodes/node_library/workflow_registry.py
  src/griptape_nodes/retained_mode/events/payload_registry.py
  src/griptape_nodes/retained_mode/griptape_nodes.py
  src/griptape_nodes/traits/trait_registry.py
  src/griptape_nodes/utils/metaclasses.py
Labels: refactor

#1210 fix: use \n\n as rule delimiter to allow for rules across multiple lines
  libraries/griptape_nodes_library/griptape_nodes_library/rules/create_ruleset.py
Labels: bug

#1240 docs: add FAQ for installing pre-release builds
  docs/faq.md
Labels: documentation

#1252 feat: add events for uploading to static server via URL
  pyproject.toml
  src/griptape_nodes/app/app.py
  src/griptape_nodes/retained_mode/events/static_file_events.py
  src/griptape_nodes/retained_mode/managers/static_files_manager.py
  uv.lock
Labels: enhancement

#1193 feat: properly parse and present image generation errors
  libraries/griptape_nodes_library/griptape_nodes_library/image/create_image.py
  libraries/griptape_nodes_library/griptape_nodes_library/utils/error_utils.py
Labels: enhancement

#1253 fix: properly respect workspace-directory passed as CLI args
  src/griptape_nodes/__init__.py
Labels: bug

#1255 fix: allow cross origin PUT requests on static server
  src/griptape_nodes/app/app.py
Labels: bug

#1290 fix: correctly parse args on fresh install
  src/griptape_nodes/__init__.py
Labels: installer

#1333 fix: remove automatic bucket provisioning
  src/griptape_nodes/drivers/storage/griptape_cloud_storage_driver.py
  src/griptape_nodes/retained_mode/managers/static_files_manager.py
Labels: bug

#1385 Standard node library's templates were resaved with an "_1" suffix; removed that.
  libraries/griptape_nodes_library/workflows/templates/compare_prompts.py
  libraries/griptape_nodes_library/workflows/templates/coordinating_agents.py
  libraries/griptape_nodes_library/workflows/templates/photography_team.py
Labels: bug
