Repository griptape-ai/griptape-nodes, pull requests merged in 2025-03, with the labels that each got.

#1 feat: improve install scripts
  install.ps1
  install.sh
  src/griptape_nodes/retained_mode/griptape_nodes.py
  src/griptape_nodes/retained_mode/managers/settings.py
Labels: enhancement

#42 fix: don't use uv version when committing
  Makefile
Labels: bug

#48 refactor: remove validations parameter
  src/griptape_nodes/exe_types/core_types.py
Labels: parameters, refactor

#49 Fix Various Install Script Quirks
  README.md
  install.sh
  src/griptape_nodes/api/app.py
  src/griptape_nodes/api/routes/nodes_api_fake_socket.py
  src/griptape_nodes/retained_mode/managers/settings.py
Labels: bug

#53 feat: add parameter validators/converters
  src/griptape_nodes/exe_types/core_types.py
  src/griptape_nodes/machines/node_resolution.py
Labels: enhancement, parameters

#60 Removed Temporary Hack for Connection Deletion
  src/griptape_nodes/exe_types/connections.py
  src/griptape_nodes/exe_types/flow.py
  src/griptape_nodes/retained_mode/griptape_nodes.py
Labels: refactor

#81 docs: update contributing guidelines to cover local dev nuances
  CONTRIBUTING.md
  README.md
Labels: documentation

#86 fix(nodes): use correct package import paths
  nodes/griptape_nodes_library/agent.py
  nodes/griptape_nodes_library/create_image.py
  nodes/griptape_nodes_library/drivers/anthropic_prompt_driver.py
  nodes/griptape_nodes_library/drivers/audio_transcription_drivers.py
  nodes/griptape_nodes_library/drivers/base_image_driver.py
  nodes/griptape_nodes_library/drivers/cohere_prompt_driver.py
  nodes/griptape_nodes_library/drivers/griptape_cloud_prompt_driver.py
  nodes/griptape_nodes_library/simple_agent.py
  nodes/griptape_nodes_library/tools/audio_transcription_tool.py
  nodes/griptape_nodes_library/tools/extraction_tool.py
Labels: bug

#87 Pull Parameter Value Through
  nodes/griptape_nodes_library/utils/reroute.py
  src/griptape_nodes/machines/node_resolution.py
  src/griptape_nodes/retained_mode/griptape_nodes.py
Labels: bug

#90 fix: solve install script issues
  install.ps1
  install.sh
Labels: bug

#91 fix: don't initalize socket until after running
  src/griptape_nodes/api/app.py
  src/griptape_nodes/api/routes/nodes_api_socket_manager.py
  uv.lock
Labels: bug

#92 feat: add startup message telling them to visit website
  src/griptape_nodes/api/app.py
  src/griptape_nodes/retained_mode/managers/log_manager.py
Labels: enhancement

#95 Wrong path to library was being echoed; was echo-ing the most recently-loaded node from the library instead of the library path.
  src/griptape_nodes/retained_mode/griptape_nodes.py
Labels: bug

#89 feat: add parameter groups
  .github/workflows/unit-tests.yml
  CONTRIBUTING.md
  Makefile
  nodes/griptape_nodes_library/agent.py
  pyproject.toml
  src/griptape_nodes/exe_types/core_types.py
  src/griptape_nodes/exe_types/node_types.py
  src/griptape_nodes/retained_mode/events/node_events.py
  src/griptape_nodes/retained_mode/events/parameter_events.py
  src/griptape_nodes/retained_mode/griptape_nodes.py
  tests/__init__.py
  tests/integration/__init__.py
  tests/integration/conftest.py
  tests/integration/retained_mode/__init__.py
  tests/integration/retained_mode/events/__init__.py
  tests/integration/retained_mode/events/test_node_events.py
  tests/unit/__init__.py
  tests/unit/exe_types/__init__.py
  tests/unit/exe_types/test_core_types.py
  uv.lock
Labels: enhancement

#110 feat: add Griptape Cloud Image Generation Node
  CONTRIBUTING.md
  Makefile
  nodes/griptape_nodes_library.json
  nodes/griptape_nodes_library/agent.py
  nodes/griptape_nodes_library/create_image.py
  nodes/griptape_nodes_library/drivers/base_image_driver.py
  nodes/griptape_nodes_library/drivers/griptape_cloud_image_driver.py
  nodes/griptape_nodes_library/drivers/griptape_cloud_prompt_driver.py
  nodes/griptape_nodes_library/drivers/openai_chat_prompt_driver.py
  nodes/griptape_nodes_library/simple_agent.py
  nodes/griptape_nodes_library/tools/prompt_summary_tool.py
  nodes/griptape_nodes_library/tools/rag_tool.py
  nodes/tests/__init__.py
  nodes/tests/integration/__init__.py
  nodes/tests/unit/__init__.py
  nodes/tests/unit/drivers/__init__.py
  nodes/tests/unit/drivers/test_griptape_cloud_image_generation_driver.py
  pyproject.toml
  uv.lock
Labels: enhancement

#114 Catch keyboard interrupt for graceful shutdown
  src/griptape_nodes/api/app.py
Labels: bug

#112 refactor(nodes): rename all nodes for consistency
  nodes/griptape_nodes_library.json
  nodes/griptape_nodes_library/agent.py
  nodes/griptape_nodes_library/create_dict.py
  nodes/griptape_nodes_library/create_image.py
  nodes/griptape_nodes_library/create_string.py
  nodes/griptape_nodes_library/drivers/anthropic_prompt_driver.py
  nodes/griptape_nodes_library/drivers/audio_transcription_drivers.py
  nodes/griptape_nodes_library/drivers/azure_openai_chat_prompt_driver.py
  nodes/griptape_nodes_library/drivers/azure_openai_image_driver.py
  nodes/griptape_nodes_library/drivers/base_driver.py
  nodes/griptape_nodes_library/drivers/base_embedding_driver.py
  nodes/griptape_nodes_library/drivers/base_image_driver.py
  nodes/griptape_nodes_library/drivers/base_prompt_driver.py
  nodes/griptape_nodes_library/drivers/cohere_prompt_driver.py
  nodes/griptape_nodes_library/drivers/griptape_cloud_image_driver.py
  nodes/griptape_nodes_library/drivers/griptape_cloud_prompt_driver.py
  nodes/griptape_nodes_library/drivers/ollama_embedding_driver.py
  nodes/griptape_nodes_library/drivers/ollama_prompt_driver.py
  nodes/griptape_nodes_library/drivers/openai_chat_prompt_driver.py
  nodes/griptape_nodes_library/drivers/openai_image_driver.py
  nodes/griptape_nodes_library/drivers/web_search_drivers.py
  nodes/griptape_nodes_library/end_flow.py
  nodes/griptape_nodes_library/key_value_pair.py
  nodes/griptape_nodes_library/load_image.py
  nodes/griptape_nodes_library/load_text.py
  nodes/griptape_nodes_library/merge_dict.py
  nodes/griptape_nodes_library/merge_texts.py
  nodes/griptape_nodes_library/rules/base_ruleset.py
  nodes/griptape_nodes_library/save_text.py
  nodes/griptape_nodes_library/simple_agent.py
  nodes/griptape_nodes_library/start_flow.py
  nodes/griptape_nodes_library/string_list.py
  nodes/griptape_nodes_library/tools/audio_transcription_tool.py
  nodes/griptape_nodes_library/tools/base_tool.py
  nodes/griptape_nodes_library/tools/calculator_tool.py
  nodes/griptape_nodes_library/tools/convert_agent_to_tool.py
  nodes/griptape_nodes_library/tools/date_time_tool.py
  nodes/griptape_nodes_library/tools/extraction_tool.py
  nodes/griptape_nodes_library/tools/file_manager_tool.py
  nodes/griptape_nodes_library/tools/prompt_summary_tool.py
  nodes/griptape_nodes_library/tools/query_tool.py
  nodes/griptape_nodes_library/tools/rag_tool.py
  nodes/griptape_nodes_library/tools/tool_list.py
  nodes/griptape_nodes_library/tools/tools.py
  nodes/griptape_nodes_library/tools/vector_store_tool.py
  nodes/griptape_nodes_library/tools/web_scraper_tool.py
  nodes/griptape_nodes_library/tools/web_search_tool.py
  nodes/griptape_nodes_library/utils/reroute.py
  nodes/tests/unit/drivers/test_griptape_cloud_image_generation_driver.py
  tests/integration/retained_mode/events/test_node_events.py
Labels: refactor

#115 Use Correct ABC Naming Convention
  event_schemas.json
  nodes/griptape_nodes_library/end_flow.py
  nodes/griptape_nodes_library/utils/reroute.py
  src/griptape_nodes/exe_types/connections.py
  src/griptape_nodes/exe_types/flow.py
  src/griptape_nodes/exe_types/node_types.py
  src/griptape_nodes/machines/control_flow.py
  src/griptape_nodes/machines/node_resolution.py
  src/griptape_nodes/node_library/library_registry.py
  src/griptape_nodes/retained_mode/events/base_events.py
  src/griptape_nodes/retained_mode/griptape_nodes.py
  uv.lock
Labels: refactor

#116 refactor: don't use underscores in class names
  README.md
  nodes/griptape_nodes_library/end_flow.py
  nodes/griptape_nodes_library/start_flow.py
  pyproject.toml
  src/griptape_nodes/api/app.py
  src/griptape_nodes/exe_types/core_types.py
  src/griptape_nodes/exe_types/node_types.py
  src/griptape_nodes/retained_mode/events/app_events.py
  src/griptape_nodes/retained_mode/events/arbitrary_python_events.py
  src/griptape_nodes/retained_mode/events/base_events.py
  src/griptape_nodes/retained_mode/events/config_events.py
  src/griptape_nodes/retained_mode/events/connection_events.py
  src/griptape_nodes/retained_mode/events/execution_events.py
  src/griptape_nodes/retained_mode/events/flow_events.py
  src/griptape_nodes/retained_mode/events/library_events.py
  src/griptape_nodes/retained_mode/events/node_events.py
  src/griptape_nodes/retained_mode/events/object_events.py
  src/griptape_nodes/retained_mode/events/os_events.py
  src/griptape_nodes/retained_mode/events/parameter_events.py
  src/griptape_nodes/retained_mode/events/script_events.py
  src/griptape_nodes/retained_mode/events/secrets_events.py
  src/griptape_nodes/retained_mode/events/validation_events.py
  src/griptape_nodes/retained_mode/griptape_nodes.py
  src/griptape_nodes/retained_mode/managers/config_manager.py
  src/griptape_nodes/retained_mode/managers/event_manager.py
  src/griptape_nodes/retained_mode/managers/os_manager.py
  src/griptape_nodes/retained_mode/retained_mode.py
  tests/integration/conftest.py
  tests/integration/retained_mode/events/test_node_events.py
Labels: refactor

#118 refactor: remove entrypoints used for testing
  nodes/griptape_nodes_library/agent.py
  nodes/griptape_nodes_library/drivers/azure_openai_image_driver.py
  nodes/griptape_nodes_library/drivers/base_image_driver.py
  nodes/griptape_nodes_library/drivers/cohere_prompt_driver.py
  nodes/griptape_nodes_library/drivers/griptape_cloud_prompt_driver.py
  nodes/griptape_nodes_library/drivers/ollama_embedding_driver.py
  nodes/griptape_nodes_library/drivers/ollama_prompt_driver.py
  nodes/griptape_nodes_library/rules/base_ruleset.py
  nodes/griptape_nodes_library/simple_agent.py
  src/griptape_nodes/exe_types/type_validator.py
Labels: refactor

#119 refactor(nodes): remove comfyui nodes
  nodes/griptape_nodes_library.json
  nodes/griptape_nodes_library/comfy_nodes.py
  scripts/comfyui_flow_branch.py
  src/griptape_nodes/retained_mode/managers/settings.py
Labels: refactor

#120 docs: remove request types from readme
  README.md
Labels: documentation

#117 Add retries on websocket connect and failures
  src/griptape_nodes/api/app.py
  src/griptape_nodes/api/routes/nodes_api_socket_manager.py
  src/griptape_nodes/retained_mode/managers/log_manager.py
Labels: enhancement

#122 fix: use correct class names in griptape nodes library
  nodes/griptape_nodes_library.json
Labels: bug

#124 feat(nodes): use griptape cloud for agent defaults
  nodes/griptape_nodes_library/agent.py
  nodes/griptape_nodes_library/tools/extraction_tool.py
Labels: enhancement

#125 feat: use rich panel for pretty starting message
  src/griptape_nodes/api/app.py
Labels: enhancement

#126 feat: default to griptape cloud image generation driver
  nodes/griptape_nodes_library/create_image.py
Labels: enhancement

#128 fix: don't forget to add the lock file
  Makefile
  uv.lock
Labels: bug

#129 fix: don't default to openai agent
  nodes/griptape_nodes_library/create_image.py
  nodes/griptape_nodes_library/simple_agent.py
Labels: bug

#97 docs: improve contributing guidelines
  CONTRIBUTING.md
  README.md
Labels: documentation

#139 fix: install nodes/scripts from latest tag
  install.ps1
  install.sh
Labels: bug
