Repository griptape-ai/griptape-nodes, pull requests merged in 2025-07, with the labels that each got.

#1635 Added Advanced Library class for library-level callbacks
  src/griptape_nodes/node_library/advanced_node_library.py
  src/griptape_nodes/node_library/library_registry.py
  src/griptape_nodes/retained_mode/managers/library_manager.py
Labels: enhancement

#1639 perf: implement faster scan of hf_cache
  libraries/griptape_nodes_advanced_media_library/diffusers_nodes_library/common/utils/huggingface_utils.py
Labels: performance

#1656 feat: load secrets into environment variables (non-overriding)
  src/griptape_nodes/retained_mode/managers/secrets_manager.py
Labels: bug

#1715 refactor: move fastapi server to dedicated module
  src/griptape_nodes/app/api.py
  src/griptape_nodes/app/app.py
  src/griptape_nodes/bootstrap/workflow_runners/subprocess_workflow_runner.py
  src/griptape_nodes/drivers/storage/local_storage_driver.py
Labels: refactor

#1758 refactor: hide uvicorn logs by default
  src/griptape_nodes/app/api.py
  src/griptape_nodes/mcp_server/server.py
Labels: refactor
