Repository griptape-ai/griptape-nodes, pull requests merged in 2025-04, with the labels that each got.

#145 fix: properly handle keyboard interrupts
  src/griptape_nodes/api/app.py
Labels: bug

#146 refactor: store config in home, not cwd
  src/griptape_nodes/retained_mode/managers/config_manager.py
  src/griptape_nodes/retained_mode/managers/settings.py
Labels: refactor

#151 feat: make the final install output pop
  install.sh
Labels: enhancement

#153 Use blocking get, not empty check
  src/griptape_nodes/api/app.py
Labels: bug

#152 fix: catch if uv is not available during the installation process
  install.ps1
  install.sh
Labels: bug

#155 Fix node types in library
  nodes/griptape_nodes_library.json
  nodes/griptape_nodes_library/drivers/audio_transcription_drivers.py
  nodes/griptape_nodes_library/drivers/azure_openai_chat_prompt_driver.py
  nodes/griptape_nodes_library/drivers/azure_openai_image_driver.py
Labels: bug

#161 fix: install gt api key to portion of config that nodes use
  install.ps1
  install.sh
Labels: bug

#163 fix: resolve many windows installation issues
  install.ps1
Labels: bug

#165 fix: stream simple agent so its output appears
  nodes/griptape_nodes_library/simple_agent.py
Labels: bug

#164 refactor: initialize config in main rather than install scripts
  install.ps1
  install.sh
  src/griptape_nodes/__init__.py
Labels: refactor

#162 feat: add auto update
  install.ps1
  install.sh
  src/griptape_nodes/__init__.py
Labels: enhancement

#166 Put engine start message to show up AFTER app initialization complete event finishes
  src/griptape_nodes/api/app.py
Labels: enhancement

#168 feat: add `gtn config list` subcommand
  src/griptape_nodes/__init__.py
  src/griptape_nodes/retained_mode/managers/config_manager.py
Labels: enhancement

#174 fix: correctly set up GT_CLOUD_API_KEY for use in nodes
  src/griptape_nodes/__init__.py
  src/griptape_nodes/retained_mode/griptape_nodes.py
  src/griptape_nodes/retained_mode/managers/config_manager.py
  src/griptape_nodes/retained_mode/managers/secrets_manager.py
Labels: bug

#177 feat: add init workflow
  src/griptape_nodes/__init__.py
  src/griptape_nodes/api/routes/nodes_api_socket_manager.py
  src/griptape_nodes/retained_mode/managers/config_manager.py
  src/griptape_nodes/retained_mode/managers/settings.py
Labels: enhancement

#186 refactor: change `make version` to `make version/publish`
  Makefile
Labels: refactor

#188 fix: write settings to file when assigning wholesale
  src/griptape_nodes/retained_mode/managers/config_manager.py
  src/griptape_nodes/retained_mode/managers/settings.py
Labels: bug

#213 adding structure to docs
  docs/assets/img/griptape_nodes_header_logo.png
  docs/nodes/overview.md
  docs/reference/glossary.md
  docs/scripting/retained_mode.md
  mkdocs.yml
Labels: documentation

#212 fix: support auto update on windows
  src/griptape_nodes/__init__.py
  src/griptape_nodes/retained_mode/managers/os_manager.py
Labels: bug

#211 refactor: improve/add error messages when getting environment variables
  src/griptape_nodes/api/app.py
  src/griptape_nodes/retained_mode/managers/secrets_manager.py
Labels: refactor

#194 fix: don't auto-update in debug mode
  Makefile
  src/griptape_nodes/__init__.py
Labels: bug

#232 fix(deps): upgrade griptape to the latest version to resolve tool serialization
  pyproject.toml
  uv.lock
Labels: bug

#239 Use Loggers Over Prints and Add Setting For Log Level
  pyproject.toml
  scripts/coloring_book.py
  scripts/prompt_an_image.py
  scripts/render_logs.py
  src/griptape_nodes/api/app.py
  src/griptape_nodes/api/routes/nodes_api_socket_manager.py
  src/griptape_nodes/exe_types/connections.py
  src/griptape_nodes/exe_types/flow.py
  src/griptape_nodes/machines/control_flow.py
  src/griptape_nodes/node_library/library_registry.py
  src/griptape_nodes/retained_mode/events/generate_request_payload_schemas.py
  src/griptape_nodes/retained_mode/griptape_nodes.py
  src/griptape_nodes/retained_mode/managers/config_manager.py
  src/griptape_nodes/retained_mode/managers/log_manager.py
  src/griptape_nodes/retained_mode/managers/os_manager.py
  src/griptape_nodes/retained_mode/managers/secrets_manager.py
  src/griptape_nodes/retained_mode/managers/settings.py
  src/griptape_nodes/retained_mode/retained_mode.py
Labels: refactor

#260 fix(install): fail install on windows if an engine instance is already running
  install.ps1
Labels: installer

#261 feat: use gh cli to avoid rate limits
  src/griptape_nodes/__init__.py
Labels: enhancement, installer

#244 Remove Ruff Rules N999 and RUF012
  pyproject.toml
  src/griptape_nodes/exe_types/core_types.py
  src/griptape_nodes/exe_types/data_types.py
  src/griptape_nodes/node_library/script_registry.py
  src/griptape_nodes/retained_mode/events/base_events.py
  src/griptape_nodes/retained_mode/events/payload_registry.py
  src/griptape_nodes/retained_mode/griptape_nodes.py
  src/griptape_nodes/traits/minmax.py
  src/griptape_nodes/traits/slider.py
  src/griptape_nodes/traits/trait_registry.py
Labels: refactor

#275 fix: update session start logs to more accurately reflect actions
  src/griptape_nodes/retained_mode/griptape_nodes.py
Labels: bug

#272 fix: log ConfigManager's loaded logs in app, not constructor
  src/griptape_nodes/api/app.py
  src/griptape_nodes/retained_mode/managers/config_manager.py
Labels: bug

#274 refactor: rename api -> app and completely restructure/document it
  src/griptape_nodes/__init__.py
  src/griptape_nodes/api/__init__.py
  src/griptape_nodes/api/app.py
  src/griptape_nodes/api/queue_manager.py
  src/griptape_nodes/api/routes/__init__.py
  src/griptape_nodes/api/routes/api.py
  src/griptape_nodes/app/.python-version
  src/griptape_nodes/app/__init__.py
  src/griptape_nodes/app/app.py
  src/griptape_nodes/app/nodes_api_socket_manager.py
  src/griptape_nodes/node_library/workflow_registry.py
  src/griptape_nodes/retained_mode/griptape_nodes.py
  src/griptape_nodes/retained_mode/managers/config_manager.py
  src/griptape_nodes/retained_mode/managers/log_manager.py
Labels: refactor

#281 revert: don't use instance fields for registries
  src/griptape_nodes/node_library/workflow_registry.py
  src/griptape_nodes/retained_mode/events/payload_registry.py
  src/griptape_nodes/traits/trait_registry.py
Labels: bug

#285 feat: add uninstall command
  src/griptape_nodes/__init__.py
Labels: enhancement

#303 style: add mdformat plugins for mkdocs, format repo
  CONTRIBUTING.md
  README.md
  docs/configuration.md
  docs/getting_started.md
  docs/index.md
  docs/nodes/dict/merge_key_value_pair.md
  docs/nodes/drivers/griptape_cloud_image_driver.md
  docs/nodes/overview.md
  docs/nodes/rules/create_ruleset.md
  docs/nodes/text/create_multiline_text.md
  docs/nodes/tools/tool_list.md
  docs/reference/glossary.md
  docs/reference/retained_mode.md
  pyproject.toml
  uv.lock
Labels: documentation

#321 Added an uninstall page, linked to it in various other places, and wrote more of an intro product page to index.md - still want to capture visuals for that shortly
  docs/faq.md
  docs/getting_started.md
  docs/index.md
  docs/nodes/overview.md
  docs/nodes/utils/reroute.md
  docs/reference/glossary.md
  docs/reference/retained_mode.md
  mkdocs.yml
Labels: documentation

#378 making custom X
  docs/how_to/making_custom_nodes.md
  docs/how_to/making_custom_scripts.md
  mkdocs.yml
Labels: documentation

#379 retained mode "rename" command
  src/griptape_nodes/retained_mode/retained_mode.py
Labels: enhancement

#382 381 add some "where am i installed?" stuff to faq + unifying some getting started/configuration content re: workspace dir
  docs/faq.md
  docs/getting_started.md
Labels: documentation

#383 CreateAgent <- docs split -> RunAgent
  docs/nodes/agents/create_agent.md
  docs/nodes/agents/run_agent.md
  docs/nodes/basic/agent.md
  docs/nodes/utils/end_flow.md
  docs/nodes/utils/start_flow.md
  mkdocs.yml
Labels: documentation

#394 lots of rough edges smoothed over
  docs/faq.md
  docs/getting_started.md
  docs/index.md
  docs/nodes/dict/create_dict.md
  docs/nodes/dict/display_dict.md
  docs/nodes/dict/key_value_pair.md
  docs/nodes/dict/merge_key_value_pair.md
  docs/nodes/drivers/griptape_cloud_image_driver.md
  docs/nodes/image/describe_image.md
  docs/nodes/number/create_float.md
  docs/nodes/number/create_int.md
  docs/nodes/number/display_float.md
  docs/nodes/number/display_int.md
  docs/nodes/overview.md
  docs/nodes/rules/ruleset_list.md
  docs/nodes/text/create_text.md
  docs/nodes/text/display_text.md
  docs/nodes/text/merge_texts.md
  docs/nodes/text/save_text.md
  docs/nodes/tools/rag_tool.md
  docs/nodes/tools/tool_list.md
  docs/nodes/tools/web_scraper_tool.md
  docs/nodes/utils/reroute.md
  docs/reference/glossary.md
  docs/reference/retained_mode.md
Labels: documentation

#409 Refactor Config Initalization
  src/griptape_nodes/__init__.py
  src/griptape_nodes/retained_mode/managers/config_manager.py
Labels: refactor, config

#410 feat: open browser automatically when starting engine
  src/griptape_nodes/__init__.py
Labels: enhancement

#421 fix: merge delta config with existing config on disk
  src/griptape_nodes/retained_mode/managers/config_manager.py
Labels: bug

#415 feat: install without git
  install.ps1
  install.sh
Labels: enhancement

#441 refactor: only open browser window on first init
  src/griptape_nodes/__init__.py
Labels: refactor

#442 Show Config Precedence
  src/griptape_nodes/__init__.py
Labels: enhancement

#444 refactor: remove pydantic settings from config parsing
  pyproject.toml
  src/griptape_nodes/retained_mode/managers/config_manager.py
  src/griptape_nodes/retained_mode/managers/settings.py
  uv.lock
Labels: refactor

#446 fix: e
  src/griptape_nodes/retained_mode/griptape_nodes.py
Labels: bug

#452 Convert the workflow samples to point straight to the GitHub .webp files while we figure out how to load them.
  workflows/compare_prompts.py
  workflows/prompt_an_image.py
  workflows/thumbnail_compare_prompts.jpeg
  workflows/thumbnail_prompt_an_image.jpeg
  workflows/thumbnail_translator.jpeg
  workflows/translator.py
Labels: settings

#449 feat: enable background work for agent nodes
  nodes/griptape_nodes_library/agents/base_agent.py
  nodes/griptape_nodes_library/agents/create_agent.py
  nodes/griptape_nodes_library/agents/run_agent.py
  src/griptape_nodes/machines/node_resolution.py
Labels: enhancement

#450 fix: update workspace prompt to reflect new settings
  src/griptape_nodes/__init__.py
Labels: bug

#469 refactor: remove api key logging
  src/griptape_nodes/__init__.py
Labels: refactor

#477 deps: remove explicit marshmallow pin in favor of bumped griptape
  pyproject.toml
  uv.lock
Labels: dependencies

#484 refactor: rename IDE to Workflow Editor
  CONTRIBUTING.md
  README.md
  src/griptape_nodes/app/app.py
Labels: refactor

#494 cleaned up wonky prompt
  workflows/translator.py
Labels: bug

#495 fixing compare_prompts
  workflows/compare_prompts.py
Labels: bug

#498 Improve/Fix App Events
  src/griptape_nodes/app/app.py
  src/griptape_nodes/retained_mode/events/app_events.py
  src/griptape_nodes/retained_mode/griptape_nodes.py
Labels: bug, enhancement

#476 Save Image node
  nodes/griptape_nodes_library.json
  nodes/griptape_nodes_library/image/load_image.py
  nodes/griptape_nodes_library/image/save_image.py
  nodes/griptape_nodes_library/utils/image_utils.py
Labels: enhancement, nodes

#525 removed "input" from allowed_modes of BaseTool
  nodes/griptape_nodes_library/tools/base_tool.py
Labels: refactor

#527 Various Event Fixes
  src/griptape_nodes/app/app.py
  src/griptape_nodes/machines/node_resolution.py
Labels: bug

#532 fix: use correct name for workflow
  workflows/templates/prompt_an_image.py
Labels: bug

#529 Image Generation Fixes
  nodes/griptape_nodes_library/image/create_image.py
Labels: bug

#534 Traits Fixes
  nodes/griptape_nodes_library/drivers/prompt/ollama_prompt_driver.py
  src/griptape_nodes/exe_types/core_types.py
  src/griptape_nodes/traits/options.py
Labels: bug

#567 refactor: improve install process
  install.ps1
  install.sh
  src/griptape_nodes/__init__.py
Labels: refactor

#571 refactor: improve error messages
  src/griptape_nodes/exe_types/flow.py
Labels: refactor

#570 feat: run describe image in background
  nodes/griptape_nodes_library/image/describe_image.py
Labels: enhancement

#578 feat: add ControlFlowCancelledEvent
  src/griptape_nodes/exe_types/flow.py
  src/griptape_nodes/retained_mode/events/execution_events.py
  src/griptape_nodes/retained_mode/griptape_nodes.py
Labels: enhancement

#569 feat: add `gtn config reset` command
  src/griptape_nodes/__init__.py
  src/griptape_nodes/retained_mode/managers/config_manager.py
Labels: enhancement

#580 fix: move process_generator from node to resolution machine context
  src/griptape_nodes/exe_types/node_types.py
  src/griptape_nodes/machines/node_resolution.py
Labels: bug

#581 refactor: move process_generator from node to resolution machine context (#580)
  src/griptape_nodes/exe_types/flow.py
  src/griptape_nodes/machines/node_resolution.py
  src/griptape_nodes/retained_mode/griptape_nodes.py
Labels: refactor

#602 refactor: make pausing message a debug log
  src/griptape_nodes/machines/node_resolution.py
Labels: refactor

#605 display image node
  nodes/griptape_nodes_library.json
  nodes/griptape_nodes_library/image/display_image.py
Labels: enhancement

#615 Fixed the confusing-ass flow creation
  src/griptape_nodes/retained_mode/griptape_nodes.py
Labels: bug

#613 fix: install workflows/scripts on fresh install
  src/griptape_nodes/__init__.py
Labels: bug

#614 fix: improve auto-restart
  src/griptape_nodes/__init__.py
Labels: bug

#629 feat: add static file serving
  CONTRIBUTING.md
  nodes/griptape_nodes_library/image/create_image.py
  pyproject.toml
  src/griptape_nodes/app/app.py
  src/griptape_nodes/exe_types/node_types.py
  src/griptape_nodes/retained_mode/managers/settings.py
  uv.lock
Labels: enhancement

#658 fix: namespace venv under python version, clean up library name
  src/griptape_nodes/retained_mode/griptape_nodes.py
Labels: bug

#657 fix: automatically use an OS-provided free port
  CONTRIBUTING.md
  src/griptape_nodes/app/app.py
Labels: bug

#679 feat: add rich handler to uvicorn
  src/griptape_nodes/app/app.py
Labels: enhancement

#678 revert: don't use OS-assigned port number
  CONTRIBUTING.md
  src/griptape_nodes/app/app.py
Labels: bug

#676 fix: add support for ImageUrlArtifact to image nodes
  nodes/griptape_nodes_library/image/create_image.py
  nodes/griptape_nodes_library/image/describe_image.py
  nodes/griptape_nodes_library/image/display_image.py
  nodes/griptape_nodes_library/image/load_image.py
  nodes/griptape_nodes_library/image/save_image.py
Labels: bug

#673 refactor: don't attempt self uninstallation on Windows
  src/griptape_nodes/__init__.py
Labels: refactor

#688 fix: specify language in RTD previews
  .github/workflows/pull-request-links.yml
Labels: bug

#689 refactor: break `griptape_nodes.py` into separate manager modules
  src/griptape_nodes/retained_mode/griptape_nodes.py
  src/griptape_nodes/retained_mode/managers/arbitrary_code_exec_manager.py
  src/griptape_nodes/retained_mode/managers/flow_manager.py
  src/griptape_nodes/retained_mode/managers/library_manager.py
  src/griptape_nodes/retained_mode/managers/node_manager.py
  src/griptape_nodes/retained_mode/managers/object_manager.py
  src/griptape_nodes/retained_mode/managers/workflow_manager.py
Labels: refactor

#695 refactor: don't ignore TRY002
  pyproject.toml
  src/griptape_nodes/app/app.py
  src/griptape_nodes/exe_types/flow.py
  src/griptape_nodes/retained_mode/griptape_nodes.py
Labels: refactor

#667 uninstall/reinstall clarifications
  docs/faq.md
  docs/getting_started.md
Labels: documentation

#719 fix: don't resume processing when cancelling
  src/griptape_nodes/machines/node_resolution.py
  src/griptape_nodes/retained_mode/managers/flow_manager.py
Labels: bug

#722 fix: cancel flow run if error starting it
  src/griptape_nodes/exe_types/flow.py
Labels: bug

#725 feat: add static files manager
  nodes/griptape_nodes_library/image/create_image.py
  nodes/griptape_nodes_library/image/save_image.py
  src/griptape_nodes/exe_types/node_types.py
  src/griptape_nodes/retained_mode/events/static_file_events.py
  src/griptape_nodes/retained_mode/griptape_nodes.py
  src/griptape_nodes/retained_mode/managers/static_files_manager.py
Labels: enhancement

#745 fix: don't allow new nodes to be created in a resolving state
  src/griptape_nodes/retained_mode/managers/node_manager.py
Labels: bug

#746 refactor: use placeholder text rather than default value
  nodes/griptape_nodes_library/convert/agent_to_tool.py
Labels: refactor

#742 fix: make safe serialize even safer
  src/griptape_nodes/exe_types/type_validator.py
Labels: bug

#743 refactor: use new uv version interface
  CONTRIBUTING.md
  Makefile
Labels: bug

#748 fix: update griptape version to support serializing structure run tool
  uv.lock
Labels: bug
